### ISSUE TITLE
Sliding in some objects

### ISSUE THREAD

**Issue by GitSRealpe** [sea-bass/ycb-tools#1]
Hi, any idea on why the objects slide?, or better, how to stop it?

We been using this data-set for a project and implemented a similar approach using **trimesh** to generate the objects properties for the SDF like you did, but some of them start sliding or having some jittering in Gazebo and we haven't found out why.

(We used a different method for the collision models with [Meshlab](https://www.meshlab.net/) and its quadric edge collapse decimation process, and also got sliding problems.)

![sliding](https://user-images.githubusercontent.com/28267340/111854173-e2e0af80-88eb-11eb-9589-2d393740afea.gif)

Also thanks for uploading this code, it was a pain for us when we had to do it.

**Comment by sea-bass** [comment]
I think downsampling the meshes randomly and not filling them will mess with the physics, as you have seen.

The better thing to do may be to manually create simple primitives (e.g. the hammer can be made of 2 boxes) and use those as the collision mesh while retaining the high-res visual meshes.

**Comment by GitSRealpe** [comment]
> The better thing to do may be to manually create simple primitives (e.g. the hammer can be made of 2 boxes) and use those as the collision mesh while retaining the high-res visual meshes.

Yep, seems like the best option, thanks for answering.
