### ISSUE TITLE
conversion of ycb to ignition gazebo models (sdf format)

### ISSUE THREAD

**Issue by addy1997** [sea-bass/ycb-tools#2]
Hi there,

The conversion, if I understand it correctly, happens on the basis of the [template](https://github.com/sea-bass/ycb-tools/blob/main/templates/ycb/template.sdf) file. If I change the file with another template supported by the [ignition gazebo ](https://ignitionrobotics.org/libs/gazebo), will I get the compatible model that ignition gazebo supports?

Thanks

**Comment by sea-bass** [comment]
That's correct. Actually, it may require little to no changes because Ignition also uses the SDF format:

https://ignitionrobotics.org/docs/all/getstarted#step-3-create-your-own-world

https://ignitionrobotics.org/api/gazebo/5.0/meshtofuel.html

If you are trying this out, it would be great to know whether this immediately works, or if there are minor changes that we can update this repo with.

**Comment by addy1997** [comment]
TL ; DR (except the 5th and 6th points)

1. The `SDF files` in the `ignition don't support .material files`. More on this [here](https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo5/tutorials/migration_sdf.md). 

2. The code works and the files (.obj and .dae) are also generated. 

3. I tested the files in the ignition gazebo and got these error (given below)
`[Err] [CustomMeshShape.cc:144] [dartsim::CustomMeshShape] One of the sub meshes [0:] in the input mesh [/home/adwaitnaik/077_rubiks_cube] does not have a normal count [0] that matches its vertex count [8832]. This submesh will be ignored!
`
4. I tried simulating the `rubiks_cube`, it worked well for the first time, and then threw the error given above. 

5. I haven't tried other files as of yet but one good thing about the code is that it generates good quality **dae and obj** files. However, the ignition gazebo prefers the (collision meshes) in `dae` format for high quality results. In this case, the `collision meshes` are in `.obj` format. This needs to be resolved.

![image](https://user-images.githubusercontent.com/29406906/115960255-f35cf900-a52d-11eb-9216-1d67682288c0.png)


6. I will share the code and files with you in case you wanna try it yourself and reprouce the issue. 

Thanks

**Comment by sea-bass** [comment]
I see. Well, the `.material` files, as well as the `.dae` and `.obj` files are directly from the dataset. The objects that have `google_16k` meshes available will have `.dae` files available, but the others only have `.obj`.

It is possible to convert them, perhaps even with the `trimesh` Python package that this repo uses... but I haven't tried.

As for the texture visual artifacts thing, I think that has to do with the `downsample_ratio` parameter which I had defaulted to `0.33` in the script. That is, I'm randomly removing 67% of the mesh vertices to speed up collision checks in Gazebo. I've found that Gazebo really doesn't like those meshes. There are probably better ways to process these meshes either with or without the `trimesh` library. While Gazebo still allowed me to employ this hack, I guess Ignition is not as tolerant.

I've now changed that to a command-line argument and defaulted it to not sample (i.e. ratio of `1.0`). In the latest push I just did, you can do, e.g.:

```
python3 create_ycb_sdf.py
python3 create_ycb_sdf.py --downsample-ratio 0.5
```

And yes, feel free to share examples! I've never tried Ignition and it's always a good time to try :)

**Comment by addy1997** [comment]
Yes, that can be tried. I will try to tweak the downsample_ratio parameter. I tried importing the downsampled.obj files in the blender and got this (downsampling_factor =0.5)

![image](https://user-images.githubusercontent.com/29406906/115973447-a3ecec00-a572-11eb-8c01-97a7aa3331c8.png)

![image](https://user-images.githubusercontent.com/29406906/115973453-b23b0800-a572-11eb-9355-24c2f46b4883.png)

**Comment by sea-bass** [comment]
Right. I'm suggesting we leave it at 1.0 so this does not happen.

**Comment by addy1997** [comment]
> Right. I'm suggesting we leave it at 1.0 so this does not happen.

Well, I hope so it works then. Anyways, thanks a lot for helping out. Here's the [template](https://drive.google.com/file/d/1P98hHaR8TXwkqWawDdtElQWsD-nNw2yf/view?usp=sharing) and [config ](https://drive.google.com/file/d/1JEtKjf6VEooReBBk_I_916zvY9scjTAU/view?usp=sharing)file for your reference.

**Comment by addy1997** [comment]
Hi @sea-bass,

So here's some improvement. Please see the image attached below. I was able to simulate the `sugar_box` in the ignition gazebo. You were correct about the value of the `downsampling factor` to be set as 1. 

![Screenshot 2021-05-12 at 12 22 01](https://user-images.githubusercontent.com/29406906/117931364-b742da00-b31c-11eb-8516-913d875e1094.png)
![Screenshot 2021-05-12 at 12 21 54](https://user-images.githubusercontent.com/29406906/117931376-bc078e00-b31c-11eb-9923-2cc2adb27fdf.png)
![Screenshot 2021-05-12 at 12 21 22](https://user-images.githubusercontent.com/29406906/117931381-bd38bb00-b31c-11eb-9e41-c7f7792e3fe0.png)
![Screenshot 2021-05-12 at 12 21 08](https://user-images.githubusercontent.com/29406906/117931383-bd38bb00-b31c-11eb-9b94-68a6911220ad.png)

## Issue

After simulation, I am` not` able to `retain the texture or the original color of the box`. You'll observe that the box `appears red`. Any suggestion on how to fix this?

**Comment by addy1997** [comment]
I was able to tweak the code and simulate the model in Ignition. My model can be found [here](https://app.ignitionrobotics.org/Gambit/fuel/models/Cracker%20Box). Thanks for your help @sea-bass .

**Comment by sea-bass** [comment]
Great to see you got a working model in Ignition -- what were the tweaks to the code, though? I'd like to see them and/or accept a pull request.

**Comment by addy1997** [comment]
> Great to see you got a working model in Ignition -- what were the tweaks to the code, though? I'd like to see them and/or accept a pull request.

All the files, i.e., SDF, config, and mesh files can be found [here](https://app.ignitionrobotics.org/Gambit/fuel/models/Cracker%20Box). I have used the template which I shared with you previously. The template contains the code.

I am closing this issue. Thanks

**Comment by sea-bass** [comment]
Thanks for pointing it out. I thought by "tweaks to the code" you had actually made changes to the Python files to automatically spit out something that worked for you. Understood now.

Just one observation: I noticed you used a `cylinder` type collision for your cracker box, but perhaps you want to consider using the `box` primitive instead?

**Comment by addy1997** [comment]
Yes, I made changes to the python files and generated the model.config and
model.sdf files. I had to omit out the .texture portion in your code.

**Comment by addy1997** [comment]
Hi @sea-bass, 
 My `ignition models` have received a `staggering number of downloads` (over `1K downloads`). You can check them [here](https://app.ignitionrobotics.org/Gambit). 

I contacted the authors of the `YCB` dataset and they reacted favorably

**Comment by sea-bass** [comment]
Nice work! Great to see that these resources are available, in demand, and that there is a path to link them from the YCB dataset website itself. Thanks for your contribution.

I've edited your post above since we must always be considerate about sharing private email exchanges on a public forum like a GitHub issue.

**Comment by addy1997** [comment]
Thanks, It didn't cross my mind. Anyways, I am sorry.
