### ISSUE TITLE
unable to load YCB texture map image to pybullet

### ISSUE THREAD

**Issue by shivanimall** [sea-bass/ycb-tools#3]
I obtained object mesh, mtl files and texture map images from YCB dataset

However, I get this following error when loading it with pybullet:
`b3Printf: Unsupported texture image format` 
any resolution for this? 
Also, noting that using these works fine with blender.

**Comment by sea-bass** [comment]
OK. Maybe you should look for a resource that helps load the YCB objects into PyBullet rather than Gazebo?

This seems promising:

https://github.com/eleramp/pybullet-object-models

**Comment by shivanimall** [comment]
yes, indeed, thank you @sea-bass for pointing that out.
