### ISSUE TITLE
The {image, mask} pair

### ISSUE THREAD

**Issue by lkevinzc** [sea-bass/ycb-tools#4]
Hi there! Thanks for the code! I've used it and downloaded the dataset. However, I could not find the mask of the objects. Could you please give suggestion where I can get the data if I want to use this for a object segmentation? Many thanks!

**Comment by sea-bass** [comment]
I think for this you would need to do your own ray intersection checks from some simulated image plane to a mesh located in the world. In other words, have a line going from your simulated camera to each pixel location and check whether it intersects with a mesh object at a known ground truth pose.

Seems like the `trimesh` package which I used for these scripts has something available for you to try?
https://trimsh.org/examples/ray.html

I've done a similar thing in the past, but only for automatically creating bounding boxes, not segmentation masks. The process below would be roughly the same, except you would care about each pixel whereas I only cared about the outer bounds of the mesh.

For this you would need 
* The mesh of a particular object (which we have in the dataset)
* The pose of the object relative to the camera frame (to transform the mesh), which you can get with the `/gazebo/get_model_state` ROS service
* The camera intrinsics (specifically the focal lengths, to know the directions of each ray that correspond to a particular pixel)

If you end up pursuing this, I'd be interested in seeing what happens!

**Comment by lkevinzc** [comment]
> I think for this you would need to do your own ray intersection checks from some simulated image plane to a mesh located in the world. In other words, have a line going from your simulated camera to each pixel location and check whether it intersects with a mesh object at a known ground truth pose.
> 
> Seems like the `trimesh` package which I used for these scripts has something available for you to try?
> https://trimsh.org/examples/ray.html
> 
> I've done a similar thing in the past, but only for automatically creating bounding boxes, not segmentation masks. The process below would be roughly the same, except you would care about each pixel whereas I only cared about the outer bounds of the mesh.
> 
> For this you would need
> 
> * The mesh of a particular object (which we have in the dataset)
> * The pose of the object relative to the camera frame (to transform the mesh), which you can get with the `/gazebo/get_model_state` ROS service
> * The camera intrinsics (specifically the focal lengths, to know the directions of each ray that correspond to a particular pixel)
> 
> If you end up pursuing this, I'd be interested in seeing what happens!

Thank you so much for the advice! I'll try and see :)
